### PR TITLE
better deployment

### PR DESCRIPTION
**Pull request by noraj**
- README: add steps for production + more clear general deployment 
- db/seed: auto confirm dev accounts

### CODE REVIEW

**Comment by rbclark** [comment]
I'm not sure if I agree with the production instructions. The most tested way of deploying the ctf-scoreboard is using Heroku, or if you want to use your own server then using https://github.com/dokku/dokku. We have deployed this scoreboard using both of these methods multiple times over the past 5 years so using these for sure works. With that said, there is some benefit to the steps that you provided for sure. 

As for the user creation, I'm pretty sure you can automatically confirm the account using `User.create(email: 'root@root.com', password: 'ChangeMe123', confirmed_at: Time.now.utc, admin: true)` (the important part being the `confirmed_at`).

**Comment by rbclark** [comment]
Just to clarify, I mean that I don't feel we should be encouraging users to deploy in production without nginx or apache.

**Comment by noraj** [comment]
@rbclark So please can you add a disclaimers where you state that the scoreboard was tested only on heroku/dokku environment. And maybe add in production install states the steps that change from what I wrote. Or totally rewrite how to deploy the scoreboard in production ?

Because actually someone that want to try the scoreboard and not familiar with RoR will fails to install it like I did and will stop using it in profit of another platform more easy to install. We should provide some good installation steps.

When I tried to confirm the default users I didn't used `confirmed_at` and it worked, how this is needed to automate the process ?

**Comment by noraj** [comment]
> Just to clarify, I mean that I don't feel we should be encouraging users to deploy in production without nginx or apache.

We should talk about that too in the README, indeed a reverse proxy will guarantee better security than exposing it directly.

**Comment by noraj** [comment]
oooops, I pushed the change for #122 in the same branch

**Pull request closed without merging**
