### PR TITLE
Development fix

### PR DESCRIPTION
**Pull request by Domur**
Fixes the development environment by updating sprockets to fix the pipeline issue that was affecting assets being loaded in the correct order. Reenabled debug mode.

### CODE REVIEW

**Comment by rbclark** [comment]
I'd really suggest against upgrading `sass-rails`, based on my experience `sass-rails` 6.0 is a real bear and should be completely avoided. With that said I'm not 100% sure what you were fixing here.

**Comment by Domur** [comment]
> 

Hey Robert, thanks for the comment. 

I think what this was addressing was that after upgrading rails_admin to 3.0.0 (to make use of Bootstrap 5) the Sprockets asset pipeline was broken for development. Files that required jQuery would sometimes be required before jQuery had fully loaded. I found that upgrading Sass and Sprockets fixed the issue, and haven't seen any problems with it so far. Why should it be avoided?

**Comment by rbclark** [comment]
Perhaps I've just been very unlucky but I've had https://github.com/sass/sassc-rails/issues/122 pop up a decent number of times across different projects with sassc and generally at the worst times possible when trying to actually deploy or causing intermittent test failures. If I'm remembering correctly it seems especially susceptible to trying to deploy the application in Dokku which I would normally use for deploying this app in production.

Looking at the current instance of the app, the only error I'm actually seeing when running the main branch is `Uncaught TypeError: filterrificForm is null`, which is being caused by filterific. I'm not sure why I pinned it to the non-jquery version previously, I think it has having another conflict at that point. When testing locally I removed `gem 'sassc-rails'` from the bottom of the gemfile and everything seemed to still be functioning properly.

**Comment by Domur** [comment]
Hmm, interesting. I'll take another look and make sure everything seems good still. Thanks for having taken the time to check in on this.

**Pull request merged**
