### PR TITLE
Broken Navbar #464

### PR DESCRIPTION
**Pull request by sesheikholeslam**
**Fixes broken navbar from issue #464:** Removes `always_link_to_if_admin` and replaces with `link_to` allowing users who are not logged in when a game is not in progress to see a proper navbar

### CODE REVIEW

**Comment by rbclark** [comment]
All the changes in `bin/` and `script/` shouldn't be necessary as part of this.

**Comment by sesheikholeslam** [comment]
> All the changes in `bin/` and `script/` shouldn't be necessary as part of this.
When I ran `rubocop` I got an offense about the CR so I removed CR in `bin/` and `script/` and I passed the local test. However, now the GitHub test environment fails and does not explain what is the cause of failure.

**Comment by rbclark** [comment]
Try resetting the branch hard to mitre-cyber-academy master and only cherry-picking that one change. Any weird file changes like that should get reset when you do that, the file permissions issues. Only `git cherry-pick b47819a3f082586cc2e64a640e822e7373ec8ca1`

**Comment by sesheikholeslam** [comment]
> Try resetting the branch hard to mitre-cyber-academy master and only cherry-picking that one change. Any weird file changes like that should get reset when you do that, the file permissions issues. Only `git cherry-pick b47819a3f082586cc2e64a640e822e7373ec8ca1`

I tried to cherry-pick but I couldn't because there were changes that I didn't make which had to be committed. So I reset my branch with `git reset --hard` and tried cherry picking but I couldn't because `git status` was saying many, if not all, of the files had been modified and must be committed before cherry picking. So I decided wiped my local master branch with the upstream/master and I closed the pull request from my old master branch. As of right now I have made a new branch based off of the upstream/master and made the fixes in the branch. However, the problem right now is the GitHub test environment's "run test" keeps failing which is stopping the PR right now.

**Comment by rbclark** [comment]
Do you still have a copy of the repository outside of the shared folder? Try using the one there since it should eliminate all of the strange filesystem errors.

**Pull request closed without merging**
